NUmPy: Numerical Python

The NumPy ndarray: A Multidimensional Array Object

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data 

array([[-0.05945511, -0.74658181,  0.51378633],
       [-0.56011356,  0.27490005, -0.0071904 ]])

In [3]:
data*10

array([[-0.59455111, -7.46581812,  5.13786327],
       [-5.60113555,  2.74900046, -0.07190401]])

In [4]:
data+data

array([[-0.11891022, -1.49316362,  1.02757265],
       [-1.12022711,  0.54980009, -0.0143808 ]])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
np.array(data2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((8,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.zeros((8,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [11]:
np.empty((8,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '.44'], dtype=np.string_)

In [21]:
numeric_strings.astype(float)

array([ 1.25, -9.6 ,  0.44])

As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection. An important first dis‐ tinction from Python’s built-in lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [22]:
arr= np.arange(10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
lst = [i for i in range(10)]

In [25]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
lst[5:8]= 12

TypeError: can only assign an iterable

In [28]:
arr[5:8] = 12

In [29]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [30]:
lst[5] = 10
lst

[0, 1, 2, 3, 4, 10, 6, 7, 8, 9]

In [31]:
arr[:]= 16

In [32]:
arr

array([16, 16, 16, 16, 16, 16, 16, 16, 16, 16])

If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array—for example, arr[5:8].copy().

In [33]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2][1]

8

In [34]:
arr2d[2,1]

8

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [36]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d_copy= arr3d[0].copy()
# arr3d_copy= 42

In [44]:
arr3d_copy

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr3d[0]= 42

In [46]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0]= arr3d_copy

In [48]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d_copy[:]= 1

#use [:] to assign values to all indexes

In [57]:
arr3d_copy

array([[1, 1, 1],
       [1, 1, 1]])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

Boolean Indexing

In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

In [67]:
names== 'Bob'

array([ True, False, False,  True, False, False, False])

In [65]:
data[names== 'Bob']

array([[-0.30182317, -0.03478062,  0.8238487 ,  0.3279162 ],
       [-0.55119154, -2.20968193,  1.29724914,  1.87615465]])

In [70]:
data

array([[-0.30182317, -0.03478062,  0.8238487 ,  0.3279162 ],
       [-0.98284209,  1.68166621, -1.79221677,  2.52628345],
       [ 1.22193552,  0.7025427 , -0.39956982,  0.18463577],
       [-0.55119154, -2.20968193,  1.29724914,  1.87615465],
       [ 1.47613447, -0.32447289, -2.45653146, -0.13610812],
       [ 0.70291183,  0.80007264, -0.5239865 ,  0.68641156],
       [-0.24772726,  0.97328162, -0.50149149, -0.54847629]])

In [73]:
data[(names== 'Bob') | (names== 'Will')]

array([[-0.30182317, -0.03478062,  0.8238487 ,  0.3279162 ],
       [ 1.22193552,  0.7025427 , -0.39956982,  0.18463577],
       [-0.55119154, -2.20968193,  1.29724914,  1.87615465],
       [ 1.47613447, -0.32447289, -2.45653146, -0.13610812]])

The Python keywords and and or do not work with boolean arrays. Use & (and) and | (or) instead.

In [74]:
data[data< 0 ]=0

In [75]:
data

array([[0.        , 0.        , 0.8238487 , 0.3279162 ],
       [0.        , 1.68166621, 0.        , 2.52628345],
       [1.22193552, 0.7025427 , 0.        , 0.18463577],
       [0.        , 0.        , 1.29724914, 1.87615465],
       [1.47613447, 0.        , 0.        , 0.        ],
       [0.70291183, 0.80007264, 0.        , 0.68641156],
       [0.        , 0.97328162, 0.        , 0.        ]])

FANCY INDEXING

In [78]:
arr= np.empty((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
for i in range(8):
    arr[i]= i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order:

In [81]:
arr[[4,2,3]]

array([[4., 4., 4., 4.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [82]:
arr[[4,4,4]]

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [83]:
arr= np.arange(32).reshape(8,4)

In [84]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

something different. Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.

In [85]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.

In [86]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Transposing Arrays and Swapping Axes

In [87]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [88]:
np.dot(arr,arr.T)

array([[  14,   38,   62,   86,  110,  134,  158,  182],
       [  38,  126,  214,  302,  390,  478,  566,  654],
       [  62,  214,  366,  518,  670,  822,  974, 1126],
       [  86,  302,  518,  734,  950, 1166, 1382, 1598],
       [ 110,  390,  670,  950, 1230, 1510, 1790, 2070],
       [ 134,  478,  822, 1166, 1510, 1854, 2198, 2542],
       [ 158,  566,  974, 1382, 1790, 2198, 2606, 3014],
       [ 182,  654, 1126, 1598, 2070, 2542, 3014, 3486]])

4.2 Universal Functions: Fast Element-Wise Array
Functions

In [89]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436]])

These are referred to as unary ufuncs. Others, such as add or maximum, take two arrays (thus, binary ufuncs) and return a single array

In [93]:
x= np.random.randn(8)
y= np.random.randn(8)
np.maximum(x,y)

array([ 0.87073557,  0.53661778, -0.48086949,  0.51891353,  0.50688852,
        2.16178105,  0.30093613,  1.95598003])

In [94]:
#mod is a ufunc but it returns 2 dimensional array, namely then decimal and the integer values

In [97]:
x= np.random.randn(8)*5

In [98]:
x

array([ -1.82763265,   4.06492021,   0.02830087,   0.86752477,
         0.58816564, -11.4168196 ,   0.87827088,   1.39050854])

In [99]:
rem, whole=np.modf(x)
rem, whole

(array([-0.82763265,  0.06492021,  0.02830087,  0.86752477,  0.58816564,
        -0.4168196 ,  0.87827088,  0.39050854]),
 array([ -1.,   4.,   0.,   0.,   0., -11.,   0.,   1.]))

Array-Oriented Programming with Arrays

In [2]:
import numpy as np
points= np.arange(-5,5,.01)


x,y = np.meshgrid(points,points)

In [3]:
x.shape

(1000, 1000)

In [5]:
x

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [6]:
y

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [8]:
z= np.sqrt(x**2, y**2)

In [23]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
^C
ERROR: Operation cancelled by user
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [22]:
import matplotlib

ModuleNotFoundError: No module named 'matplotlib'